### ISSUE TITLE
No tree for non-admin-user with TYPO3 v9.5.19

### ISSUE THREAD

**Issue by joneppie** [bueroparallel/bp_pagetree#2] opened 2020-06-09 13:08 UTC
With TYPO3 version 9.5.19 non-admin-user has no page-tree. Loading fails.

**Comment by dev-rke** [comment] 2020-06-10 20:26
I can confirm this issue, it is caused by changed method signatures.
I added a pull request that aligns method signatures.
A short test caused no new issues, it seems to work as before.

As long as the patch is not merged, you might use https://github.com/cweagans/composer-patches to use my patch within your project.

**Comment by th-f** [comment] 2020-06-15 17:07
Thanks to @dev-rke this has now been fixed, the fix should not break older 9.5 installations (verified on 9.5.8).

**Closed as completed by th-f** 2020-06-15 17:07 UTC

**Comment by dev-rke** [comment] 2020-06-16 00:35
Hi @th-f ,

thanks for the fast review and merge process.
Furthermore i would like to thank for the extension itself, it saved me a lot of headache on upgrading to 9.5 a few months ago! :-)
